
import type { Metadata } from "next";
import { Metrophobic } from "next/font/google";
import "./globals.css";
import { Provider } from 'react-redux';  // Import Redux Provider
import store from "@/Redux/Store";  // Adjust the path to your store file

const inter = Metrophobic({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
          {children}
        
      </body>
    </html>
  );
}

